### ISSUE TITLE
Migrate to Orb Tools v11

### ISSUE THREAD

**Issue by EricRibeiro** [CircleCI-Public/aws-elastic-beanstalk-orb#18]
## Describe Request:
Migrate to Orb Tools v11.1

## Supporting Documentation Links:
https://github.com/CircleCI-Public/orb-tools-orb/blob/master/MIGRATION.md

**Comment by yaningo** [comment]
@CircleCI-Public/cpeng, I've been working on this.

[Here's](https://github.com/yaningo/aws-elastic-beanstalk-orb/tree/parametrizor) what I have so far.

**Note:** Modifications also include a new feature to allow users to set up their EB CLI for multiple environments (leveraging AWS CLI named profiles).

**Comment by brivu** [comment]
Hey @yaningo, 

Thank you for your contribution! We took care of this in PR #28 so we'll be closing this. 

Thanks again!
