### ISSUE TITLE
Error installing awsebcli

### ISSUE THREAD

**Issue by twbarber** [CircleCI-Public/aws-elastic-beanstalk-orb#22]
## What happened:

EB CLI Setup failes with error.

```
installing awsebcli...
Fatal error from pip prevented installation. Full pip output in file:
    /home/circleci/.local/pipx/logs/cmd_2022-11-23_17.43.46_pip_errors.log

pip seemed to fail to build package:
    awsebcli

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    AttributeError: module 'distutils.log' has no attribute 'warning'
    error: metadata-generation-failed

Error installing awsebcli.


Exited with code exit status 1
```

## Expected behavior:

Orb should successfully install awsebcli

## Additional Information

![Screenshot 2022-11-23 at 1 30 12 PM](https://user-images.githubusercontent.com/1761881/203622395-bed3cb80-b6c4-4450-b886-c8d8841d62f2.png)

**Comment by twbarber** [comment]
Appears [numpy had a similar issue recently](https://github.com/numpy/numpy/issues/22623), and root cause was related to [a change](https://github.com/pypa/setuptools/commit/74652cabdeaacadc76ccf126563bed8ee2ccf3ef) in `setuptools`.

**Comment by moogsG** [comment]
Looking into pipx, it appears that it forces an update of `setuptools` when it creates the shared libs. 
https://github.com/pypa/pipx/blob/main/src/pipx/shared_libs.py#L98

**Comment by moogsG** [comment]
Adding this PR from `setuptools` as it will fix the issue.
https://github.com/pypa/setuptools/pull/3709

**Comment by twbarber** [comment]
This issue was resolved with the fix mentioned by @moogsG - closing this issue as Solved.
