### ISSUE TITLE
Orb command "setup"   failing in CI

### ISSUE THREAD

**Issue by mrexhepi** [CircleCI-Public/aws-elastic-beanstalk-orb#23]
## Orb circleci/aws-elastic-beanstalk@2

Command "setup" out of the orb is failing in the CI, due to packages on packagecloud.io not accessible anymore,
```
E: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/jammy/InRelease 402 Payment Required [IP: 52.8.159.246 443]
E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu jammy InRelease' is not signed.
```

## Additional Information:
See issue: https://github.com/git-lfs/git-lfs/issues/5197 
I think some kind of same solution needs to be set in the orb config as well.

**Comment by mrexhepi** [comment]
cc: @polymeris @sulami @sulami @Jaryt

**Comment by brivu** [comment]
Hey @mrexhepi - I took at this orb and tested the `setup` command and it looks like it's working. 

The issue you linked has also been resolved. I'm closing this for now but feel free to reopen if you still have issues.
