### ISSUE TITLE
Error installing awsebcli ... again 

### ISSUE THREAD

**Issue by KrbAlmryde** [CircleCI-Public/aws-elastic-beanstalk-orb#24]
Encountering a similar issue to  https://github.com/CircleCI-Public/aws-elastic-beanstalk-orb/issues/22 with the prime difference appearing to be a missing `requirements.txt` file. 

## Orb version:
circleci/aws-elastic-beanstalk@2.0.1

## What happened:
EB CLI Setup failes with error.
```
installing awsebcli...
Fatal error from pip prevented installation. Full pip output in file:
    /home/circleci/.local/pipx/logs/cmd_2023-02-28_21.16.11_pip_errors.log

pip seemed to fail to build package:
    awsebcli

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    error: metadata-generation-failed

Error installing awsebcli.
```

## Expected behavior:
Orb should successfully install awsebcli

## Additional Information:
There is this [breadcrumb](https://github.com/aws/aws-elastic-beanstalk-cli-setup/commit/7f7f9c92762cf7622e355d9c19546fa8eb96a7d0)

![Screenshot 2023-02-28 at 3 31 55 PM](https://user-images.githubusercontent.com/3466961/221985033-f88e2281-1ba9-4cc9-aee9-c1a3929e6a76.png)

**Comment by alexey10** [comment]
We have the same error - blocks our deployments.

**Comment by reneherounit** [comment]
Same here! Is there any feedback or workaround for this?

**Comment by KrbAlmryde** [comment]
It appears this issue has been resolved. Will close this issue. Thanks!
