### ISSUE TITLE
Unable to locate package python3-venv

### ISSUE THREAD

**Issue by vladanzivanovic** [CircleCI-Public/aws-elastic-beanstalk-orb#6]
## Additional Information:

The messages from circleci are: 
Python3 env found
pip found
E: Unable to locate package python3-venv

`jobs:`

> `build-and-push-eb-deployable:`

>> `steps:`
>>> `- checkout`
>>> `- aws-eb/setup`

**Comment by gmemstr** [comment]
@vladanzivanovic Which execution environment (docker/machine/macos) are you using in this case?

**Comment by vladanzivanovic** [comment]
> @vladanzivanovic Which execution environment (docker/machine/macos) are you using in this case?

@gmemstr Machine Linux Medium Ubuntu 14.04

**Comment by dsayling** [comment]
python3 is not installed on Ubuntu 14.04, you'll need a later executor
